In [1]:
import numpy as np
yes=np.array([[1,2,3],
              [4,2,3],
              [9,3,4]])
print("orginal array")
print(yes)

nextyes=yes.reshape(9,1)
print("reshaped arr:")
print(nextyes)

next2yes=yes.reshape(1,9)
print("reshaped arr:")
print(next2yes)

next3yes=yes.reshape(3,3)
print("reshaped arr:")
print(next3yes)




orginal array
[[1 2 3]
 [4 2 3]
 [9 3 4]]
reshaped arr:
[[1]
 [2]
 [3]
 [4]
 [2]
 [3]
 [9]
 [3]
 [4]]
reshaped arr:
[[1 2 3 4 2 3 9 3 4]]
reshaped arr:
[[1 2 3]
 [4 2 3]
 [9 3 4]]
